"""question_notes + question_bookmarks 笔记与收藏

Revision ID: 32982449dc95
Revises: 9b0809389580
Create Date: 2026-07-24 01:53:36.854133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32982449dc95'
down_revision = '9b0809389580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_bookmark_user_question')
    )
    with op.batch_alter_table('question_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_bookmarks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bookmarks_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('question_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_note_user_question')
    )
    with op.batch_alter_table('question_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_notes_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_notes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_notes_question_id'))

    op.drop_table('question_notes')
    with op.batch_alter_table('question_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_bookmarks_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_bookmarks_created_at'))

    op.drop_table('question_bookmarks')
    # ### end Alembic commands ###
