"""内容发现:题单 question_lists + question_list_items

Revision ID: 3c36511153bc
Revises: 43c785686003
Create Date: 2026-07-23 19:09:33.372276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c36511153bc'
down_revision = '43c785686003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_lists_is_official'), ['is_official'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_lists_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_lists_owner_id'), ['owner_id'], unique=False)

    op.create_table('question_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['question_lists.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'question_id', name='uq_list_question')
    )
    with op.batch_alter_table('question_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_list_items_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_list_items_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_list_items_list_id'))

    op.drop_table('question_list_items')
    with op.batch_alter_table('question_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_lists_owner_id'))
        batch_op.drop_index(batch_op.f('ix_question_lists_is_public'))
        batch_op.drop_index(batch_op.f('ix_question_lists_is_official'))

    op.drop_table('question_lists')
    # ### end Alembic commands ###
