"""内容发现:tags + question_tags 规范化知识点标签

Revision ID: 43c785686003
Revises: 7178d9c38a80
Create Date: 2026-07-23 18:57:56.288205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c785686003'
down_revision = '7178d9c38a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_tag_name_category')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=False)

    op.create_table('question_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'tag_id', name='uq_question_tag')
    )
    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_tags_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_question_tags_question_id'))

    op.drop_table('question_tags')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_category'))

    op.drop_table('tags')
    # ### end Alembic commands ###
