"""学习闭环:question_progress 表 + error_book SM-2 列

Revision ID: 7178d9c38a80
Revises: b7c1e2a9f34d
Create Date: 2026-07-23 18:15:15.007356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7178d9c38a80'
down_revision = 'b7c1e2a9f34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_progress_user_question')
    )
    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_progress_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_progress_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('error_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ease', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('interval_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_error_book_due_at'), ['due_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_book_due_at'))
        batch_op.drop_column('last_reviewed_at')
        batch_op.drop_column('due_at')
        batch_op.drop_column('repetitions')
        batch_op.drop_column('interval_days')
        batch_op.drop_column('ease')

    with op.batch_alter_table('question_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_progress_updated_at'))
        batch_op.drop_index(batch_op.f('ix_question_progress_question_id'))

    op.drop_table('question_progress')
    # ### end Alembic commands ###
