"""answer_submissions 采点判题提交表

Revision ID: 9b0809389580
Revises: 8ee0ed2463da
Create Date: 2026-07-24 01:32:55.478257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0809389580'
down_revision = '8ee0ed2463da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('image_paths', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('rubric_breakdown', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('grader', sa.String(length=16), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submissions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_answer_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_answer_submissions_question_id'))
        batch_op.drop_index(batch_op.f('ix_answer_submissions_created_at'))

    op.drop_table('answer_submissions')
    # ### end Alembic commands ###
