"""初始 schema:users/questions/error_book/feedback/view_logs

Revision ID: 9b0a862a7948
Revises: 
Create Date: 2026-07-06 21:18:32.404668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0a862a7948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('chapter', sa.String(length=128), nullable=True),
    sa.Column('difficulty', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('question_latex', sa.Text(), nullable=True),
    sa.Column('question_image', sa.String(length=256), nullable=True),
    sa.Column('solution_latex', sa.Text(), nullable=True),
    sa.Column('solution_image', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_subject'), ['subject'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('error_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_user_question')
    )
    with op.batch_alter_table('error_book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_book_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_book_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('view_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('view_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_view_logs_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_view_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_view_logs_viewed_at'), ['viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('view_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_view_logs_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_view_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_view_logs_question_id'))

    op.drop_table('view_logs')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_status'))

    op.drop_table('feedback')
    with op.batch_alter_table('error_book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_book_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_book_question_id'))

    op.drop_table('error_book')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_source'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_questions_created_at'))
        batch_op.drop_index(batch_op.f('ix_questions_chapter'))

    op.drop_table('questions')
    # ### end Alembic commands ###
