"""generated_files 产物属主表

Revision ID: e68cf6bac6d8
Revises: 9b0a862a7948
Create Date: 2026-07-06 22:51:54.607893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68cf6bac6d8'
down_revision = '9b0a862a7948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_files_filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('ix_generated_files_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_generated_files_filename'))
        batch_op.drop_index(batch_op.f('ix_generated_files_created_at'))

    op.drop_table('generated_files')
    # ### end Alembic commands ###
