"""字体子集化流水线:语料收集 → 合并兜底 → 子集 woff2 → @font-face/CSS → 覆盖校验/度量。

产物(static/fonts/*.subset.woff2、static/css/fonts.css)由本脚本 main() 生成,
但权威产物应以生产语料另行构建,不随本脚本入库。
"""
import sqlite3, re, pathlib, subprocess, sys
ROOT = pathlib.Path(__file__).resolve().parents[1]

ASCII_PRINTABLE = set(chr(c) for c in range(0x20, 0x7f))
# CJK/全角标点(\u 转义,勿改成字面量)
# 、。「」『』・ー〜（）【】《》，．！？：；…
CJK_PUNCT = set(
    "、。「」『』・ー〜"
    "（）【】《》，．！？"
    "：；…　"
)

# fam, 文件前缀, 脚本(cn/jp), [(font-weight, 源文件名, 输出后缀)], fallback local() 列表
FONT_TABLE = [
  ("LXGW WenKai", "lxgw-wenkai", "cn",
     [("400","LXGWWenKai-Regular.ttf","regular"),("500 700","LXGWWenKai-Medium.ttf","medium")],
     ["Songti SC","STSong","serif"]),
  ("Klee One", "klee-one", "jp",
     [("400","KleeOne-Regular.ttf","regular"),("500 700","KleeOne-SemiBold.ttf","semibold")],
     ["Hiragino Mincho ProN","Yu Mincho","serif"]),
  ("Noto Sans SC", "noto-sans-sc", "cn",
     [("400","NotoSansSC-Regular.ttf","regular"),("500","NotoSansSC-Medium.ttf","medium")],
     ["PingFang SC","Microsoft YaHei","sans-serif"]),
  ("Shippori Mincho", "shippori-mincho", "jp",
     [("400","ShipporiMincho-Regular.ttf","regular"),("700","ShipporiMincho-Bold.ttf","bold")],
     ["Hiragino Mincho ProN","Yu Mincho","serif"]),
]

# 语料字段(按需容错:源库可能尚未落 solution_ja 列)
CORPUS_FIELDS = ("question_latex", "solution_latex", "solution_ja")


def read_question_rows(db_path):
    con = sqlite3.connect(db_path); con.row_factory = sqlite3.Row
    try:
        have = {r[1] for r in con.execute("PRAGMA table_info(questions)")}
        cols = [c for c in CORPUS_FIELDS if c in have] or list(CORPUS_FIELDS)
        cur = con.execute(f"SELECT {', '.join(cols)} FROM questions")
        return [dict(r) for r in cur.fetchall()]
    finally:
        con.close()


# 平假名/片假名 ぀-ヿ、CJK 统一 一-鿿、半角/全角形 ＀-￯
CJK_SCAN = re.compile(r"[぀-ヿ一-鿿＀-￯]+")
def _scan_ui_strings():
    out = set()
    for base in ("templates", "static/js"):
        d = ROOT/base
        if not d.exists(): continue
        for p in d.rglob("*"):
            if p.suffix in (".html", ".js") and p.is_file():
                for m in CJK_SCAN.findall(p.read_text(encoding="utf-8", errors="ignore")):
                    out.update(m)
    return out


def extract_corpus(db_path, ui_strings=None):
    chars = set()
    for row in read_question_rows(db_path):
        for field in CORPUS_FIELDS:
            if row.get(field):
                chars.update(row[field])
    chars.update(_scan_ui_strings())
    for s in (ui_strings or []):
        chars.update(s)
    return chars


def _is_control(ch):
    # C0 控制符/DEL/C1(\n \t 等)无字形,永不进覆盖要求,否则语料含换行即误判缺字
    cp = ord(ch)
    return cp < 0x20 or 0x7f <= cp < 0xa0


def charset_for_font(script, corpus, cn_fallback, jp_fallback):
    base = set(corpus) | ASCII_PRINTABLE | CJK_PUNCT
    base |= (cn_fallback if script == "cn" else jp_fallback)
    return {c for c in base if not _is_control(c)}


def subset_font(src, chars, out):
    out = pathlib.Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    unicodes = ",".join(f"U+{ord(c):04X}" for c in sorted(chars))
    cmd = [sys.executable, "-m", "fontTools.subset", str(src),
           f"--unicodes={unicodes}", "--flavor=woff2",
           "--layout-features=*", "--no-hinting", f"--output-file={out}"]
    subprocess.run(cmd, check=True, capture_output=True, text=True)


def verify_coverage(cmap_codepoints, required):
    return {c for c in required if ord(c) not in cmap_codepoints}


def fallback_metrics(src):
    from fontTools.ttLib import TTFont
    f = TTFont(src); upm = f["head"].unitsPerEm; os2 = f["OS/2"]
    asc = os2.sTypoAscender/upm; desc = abs(os2.sTypoDescender)/upm
    return {"ascent": f"{asc*100:.1f}%", "descent": f"{desc*100:.1f}%", "size_adjust": "100%"}


def emit_fontface_css(metrics=None):
    metrics = metrics or {}
    lines = ["/* auto-generated by scripts/build_fonts.py -- do not edit */"]
    for fam, prefix, script, weights, fbs in FONT_TABLE:
        for w, srcname, suf in weights:
            lines.append(f"@font-face{{font-family:'{fam}';"
                         f"src:url('/static/fonts/{prefix}-{suf}.subset.woff2') format('woff2');"
                         f"font-weight:{w};font-display:swap;}}")
        m = metrics.get(fam, {})
        adj = (f"size-adjust:{m.get('size_adjust','100%')};"
               f"ascent-override:{m.get('ascent','normal')};"
               f"descent-override:{m.get('descent','normal')};line-gap-override:0%;")
        local = ",".join(f"local('{x}')" for x in fbs)
        lines.append(f"@font-face{{font-family:'{fam} Fallback';src:{local};{adj}}}")
    return "\n".join(lines) + "\n"


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(ROOT/"instance/question_bank.db"))
    ap.add_argument("--corpus-file")
    a = ap.parse_args()
    cn_fb = set((ROOT/"scripts/charset_cn.txt").read_text("utf-8"))
    jp_fb = set((ROOT/"scripts/charset_jp.txt").read_text("utf-8"))
    corpus = set(pathlib.Path(a.corpus_file).read_text("utf-8")) if a.corpus_file else extract_corpus(a.db)
    from fontTools.ttLib import TTFont
    metrics = {}
    for fam, prefix, script, weights, fbs in FONT_TABLE:
        chars = charset_for_font(script, corpus, cn_fb, jp_fb)
        for w, srcname, suf in weights:
            src = ROOT/f"fonts_src/{srcname}"
            out = ROOT/f"static/fonts/{prefix}-{suf}.subset.woff2"
            subset_font(src, chars, out)
            miss = verify_coverage(set(TTFont(out).getBestCmap()), chars)
            if miss:
                raise SystemExit(f"[missing glyphs] {out.name}: {''.join(sorted(miss))[:50]}")
        metrics[fam] = fallback_metrics(ROOT/f"fonts_src/{weights[0][1]}")
    (ROOT/"static/css/fonts.css").write_text(emit_fontface_css(metrics), "utf-8")
    print("build done")


if __name__ == "__main__":
    main()
